# Generated by Django 5.0.1 on 2026-01-18 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AttackerCard', models.IntegerField()),
                ('DefenderCard', models.IntegerField(blank=True, null=True)),
                ('isBiggerScoreWin', models.BooleanField(default=True)),
                ('isGameOngoing', models.BooleanField(default=True)),
                ('Attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_games', to=settings.AUTH_USER_MODEL)),
                ('Defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defend_games', to=settings.AUTH_USER_MODEL)),
                ('Winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
